apiVersion: v1
kind: Service
metadata:
  name: zmt-svc1
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32852     # -> here you can specify the node port number, if not specified, Kubernetes will assign a random port in the range 30000-32767