apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: cont1
      image: ubuntu
      args:
        - /bin/bash
        - -c
        - "while true; do echo Hello; sleep 10; done"
        - "touch /tmp/nikhil.txt; sleep 30; done"
  livenessProbe:
    exec:
      command:
        - cat
        - /tmp/nikhil.txt
    initialDelaySeconds: 5  # -> waits for 5 seconds before starting the probe
    periodSeconds: 5        # -> checks the liveness of the container every 5 seconds
    timeoutSeconds: 30      # -> times out after 30 seconds if the probe fails and restarts the container